---
variables:
  DOCKERHUB_REPO_NAME: swarm-launcher
  GITHUB_REPO_NAME: ix-ai/swarm-launcher
  ENABLE_AMD64: 'true'
  ENABLE_ARM64: 'true'
  ENABLE_ARMv7: 'true'
  ENABLE_ARMv6: 'true'
  ENABLE_386: 'true'

include:
  - project: 'ix.ai/ci-templates'
    file: '/bash-project.yml'
